server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOM-SERVICE
          predicates:
            - Path= /api/customers/**
        - id: r2
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path= /api/products/**
